# Generated by Django 5.0.4 on 2024-04-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
