# Generated by Django 5.0.4 on 2024-04-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
