# Generated by Django 5.0.4 on 2024-06-12 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_venta_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='nota_credito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.boleta')),
            ],
        ),
    ]
