# Generated by Django 5.0.4 on 2024-06-21 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0009_carrito_carritoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
