# Generated by Django 5.0.4 on 2024-06-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_alter_boleta_cliente_alter_boleta_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.venta'),
        ),
        migrations.CreateModel(
            name='BoletaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.boleta')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
        ),
    ]
